import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve, sep } from "node:path";
import { Inject, Injectable } from "@nestjs/common";
import { APP_CONFIG, type AppConfig } from "../common/config";

/** Where uploaded files live. Implemented on local disk now; an S3-compatible adapter replaces it later. */
export abstract class ObjectStorage {
  abstract put(key: string, data: Buffer): Promise<void>;
  abstract get(key: string): Promise<Buffer | null>;
}

@Injectable()
export class LocalDiskStorage extends ObjectStorage {
  private readonly root: string;

  constructor(@Inject(APP_CONFIG) config: AppConfig) {
    super();
    this.root = resolve(config.STORAGE_DIR);
  }

  private pathFor(key: string): string {
    // Keys are generated by the server, never taken from users; still refuse anything that escapes the root.
    const target = resolve(join(this.root, key));
    if (!target.startsWith(this.root + sep)) throw new Error("Invalid storage key");
    return target;
  }

  async put(key: string, data: Buffer): Promise<void> {
    const target = this.pathFor(key);
    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, data, { mode: 0o600 });
  }

  async get(key: string): Promise<Buffer | null> {
    try {
      return await readFile(this.pathFor(key));
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === "ENOENT") return null;
      throw error;
    }
  }
}
